baseURL = "https://docs.shift2bikes.org/"
languageCode = "en-us"
title = "shift2bikes website reboot"
theme = "gohugo-theme-ananke"

[params]
  editURL = "/admin/#/collections/"
  description = "Shift website reboot documents"
  disableAssetsBusting = true # netlify doesn't need that
  enableGitInfo = true


# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]
