version: "2"

volumes:
  db: {}
  

services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./app/build/:/var/www/app/
      - ./site/public/:/var/www/site/
      - ./legacy/cal/:/var/www/cal/
      - ./legacy/:/opt/legacy/
      - ./services/nginx/:/opt/services/nginx/
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    links:
      - node
      - php
    environment:
      - NGINX_CERT_NAME
      - NGINX_COMMON_NAME
    ports:
      - "${NGINX_HTTPS_PORT}:443"
    entrypoint: /opt/services/nginx/entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]

  db:
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    volumes:
      - db:/var/lib/mysql/
    ports:
      - 3306

  node: &node
    image: node:8
    user: "node"
    working_dir: /home/node/app/
    environment:
      - NODE_ENV=production
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
    volumes:
      - ./services/node/:/opt/services/node/
      - ./app:/home/node/app/
    links:
      - db
    expose:
      - "8081"
    entrypoint: /opt/services/node/entrypoint.sh
    command: "npm run start"
  
  webpack:
    << : *node
    expose: []
    command: "npm run build"
  
  hugo:
    image: jojomi/hugo:0.37
    volumes:
      - ./site/:/src/
      - ./site/public/:/output/
    command: "hugo -v"
  
  php:
    restart: never
    image: php:5.6-fpm
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    links:
      - db
    volumes:
      - ./legacy/:/opt/legacy/
      - ./services/php/:/opt/services/php/
    entrypoint: /opt/services/php/entrypoint.sh
    command: php-fpm
