version: "2"

volumes:
  db: {}


services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./site/public/:/var/www/site/
      - ./legacy/cal/:/var/www/cal/
      - ./legacy/:/opt/legacy/
      - "${EVENTIMAGES}:/opt/legacy/eventimages"
      - ./services/nginx/:/opt/services/nginx/
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ${LETSENCRYPT_WEBROOT}:/tmp/letsencrypt-auto
    links:
      - php
    environment:
      - NGINX_CERT_NAME
      - NGINX_COMMON_NAME
    ports:
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_HTTP_PORT}:80"
    entrypoint: /opt/services/nginx/entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]

  db:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    volumes:
      - db:/var/lib/mysql/
    ports:
      - 3306

  hugo:
    image: jojomi/hugo:0.37
    volumes:
      - ./site/:/src/
      - ./site/public/:/output/
    command: "hugo -v"

  php:
    restart: never
    image: php:5.6-fpm
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - EVENTIMAGES
    links:
      - db
    volumes:
      - ./legacy/:/opt/legacy/
      - ./services/php/:/opt/services/php/
      - "${EVENTIMAGES}:/opt/legacy/eventimages"
    entrypoint: /opt/services/php/entrypoint.sh
    command: php-fpm
