# build settings for netlify

# [build] and [build.environment] are defaults, will apply to all builds unless overridden in a context stanza below
[build]

  base = "site/"
  publish = "site/public/"

[build.environment]
  HUGO_VERSION = "0.37.1"
  SHIFT_LEGACYCAL_SERVICEURL="https://api.shift2bikes.org/api/"

[context.deploy-preview]
  # this command builds draft content for deploy previews
  command = 'hugo -D && cp public/404/index.html public/404.html'

[context.branch-deploy]
  # this command builds draft content for deploy previews
  command = 'hugo -D  && cp public/404/index.html public/404.html'

[context.production]
  # drafts are excluded (no `-D` option to hugo) for prod build
  command = 'hugo && cp public/404/index.html public/404.html && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org "cd /opt/shift-docs && ./shift pull"'

[[redirects]]
  from = "/addevent/*"
  to = "/addevent"
  status = 200
[[redirects]]
  from = "/calendar/*"
  to = "/calendar"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://api.shift2bikes.org/api/:splat"
  status = 200
