# build settings for netlify

# [build] and [build.environment] are defaults, will apply to all builds unless overridden in a context stanza below
[build]
  
  base = "site/"
  publish = "site/public/"
  command = 'hugo && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org touch authenticated'
  
[build.environment]
  HUGO_VERSION = "0.37.1"
  SHIFT_LEGACYCAL_SERVICEURL="https://api.shift2bikes.org/fun/"

[context.deploy-preview]  
  # this command builds draft content for deploy previews
  command = 'hugo -D && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org touch authenticated'

[context.branch-deploy]  
  # this command builds draft content for deploy previews
  command = 'hugo -D && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org touch authenticated'

[context.production]
  # drafts are excluded (no `-D` option to hugo) for prod build
  command = 'hugo && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org touch authenticated'
