# build settings for netlify

[build]
  
  command = "hugo && mkdir ~/.ssh && wget -O ~/.ssh/id_rsa https://${KEY_HOST}/yup.txt && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org touch authenticated"
  base = "site/"
  publish = "site/public/"
  
[build.environment]
  HUGO_VERSION = "0.37.1"
  SHIFT_LEGACYCAL_SERVICEURL="https://api.shift2bikes.org/fun/"

  
