# build settings for netlify

# [build] and [build.environment] are defaults, will apply to all builds unless overridden in a context stanza below

[build]

  base = "site/"
  publish = "site/public/"

[build.environment]
  HUGO_VERSION = "0.37.1"

[context.deploy-preview]
  # this command builds draft content for deploy previews
  command = 'hugo -D && cp public/404/index.html public/404.html'

[context.branch-deploy]
  # this command builds draft content for branches
  command = 'hugo -D  && cp public/404/index.html public/404.html'

[context.production]
  # drafts are excluded (no `-D` option to hugo) for prod build.  We also pull new code to the server in this case!
  command = 'hugo && cp public/404/index.html public/404.html && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.bikeslist.org "cd /opt/shift-docs && ./shift pull"'


## domain redirects to serve from the CDN and canonicalize
## must be first redirects in this file!

# dynamic back end + event images stored over here.  Solves CORS problems to proxy.
[[redirects]]
  from = "/api/*"
  to = "https://api.bikeslist.org/api/:splat"
  status = 200
[[redirects]]
  from = "/eventimages/*"
  to = "https://api.bikeslist.org/eventimages/:splat"
  status = 200

# testing out a special redirect for a URL that someone made up
[[redirects]]
  from = "/calendar/pedalpalooza"
  to = "/pages/pedalpalooza"
  status = 301
  
# remove-add trailing slashes kinda?  fool can't really believe this works :P
[[redirects]]
  from = "/addevent/*"
  to = "/addevent"
  status = 200
[[redirects]]
  from = "/calendar/*"
  to = "/calendar"
  status = 200

# old pedalpalooza page should link to new one
[[redirects]]
  from = "/pedalpalooza"
  to = "/pages/pedalpalooza"
  status = 301

